INITIAL_PRODUCTS = [
    {
        "id": "bloco-est-14-39-45",
        "codigo": "BE-1439-4.5",
        "nome": "Bloco Estrutural 14x19x39 cm (4.5 MPa)",
        "categoria": "blocos-estruturais",
        "categoria_label": "Blocos Estruturais",
        "destaque": True,
        "dimensoes": "14 x 19 x 39 cm",
        "resistencia": "4.5 MPa",
        "peso": "11.8 kg",
        "rendimento": "12.5 un / m²",
        "paletizacao": "120 peças / pallet",
        "norma": "ABNT NBR 6136 - Classe B",
        "unidade": "un",
        "qtd_minima": 100,
        "incremento": 50,
        "pronta_entrega": True,
        "descricao_curta": "Padrão ouro para alvenaria estrutural de sobrados e galpões.",
        "descricao_longa": "Bloco de concreto vazado de alta precisão dimensional e excelente acabamento superficial. Reduz o consumo de argamassa no assentamento e acelera o tempo de execução da obra.",
        "aplicacoes": ["Alvenaria estrutural autoportante", "Muros de contenção e arrimo", "Galpões comerciais e industriais"],
        "tipo_icone": "bloco-padrao"
    },
    {
        "id": "bloco-est-14-39-80",
        "codigo": "BE-1439-8.0",
        "nome": "Bloco Estrutural 14x19x39 cm (8.0 MPa)",
        "categoria": "blocos-estruturais",
        "categoria_label": "Blocos Estruturais",
        "destaque": False,
        "dimensoes": "14 x 19 x 39 cm",
        "resistencia": "8.0 MPa",
        "peso": "13.2 kg",
        "rendimento": "12.5 un / m²",
        "paletizacao": "108 peças / pallet",
        "norma": "ABNT NBR 6136 - Classe A",
        "unidade": "un",
        "qtd_minima": 100,
        "incremento": 50,
        "pronta_entrega": True,
        "descricao_curta": "Alta resistência para edifícios multipavimentos e cargas elevadas.",
        "descricao_longa": "Desenvolvido para construções de múltiplos pavimentos que exigem alta capacidade de suporte à compressão axial.",
        "aplicacoes": ["Prédios residenciais de múltiplos pavimentos", "Pilares grauteados", "Fundamentos de alta carga"],
        "tipo_icone": "bloco-padrao"
    },
    {
        "id": "bloco-est-19-39-60",
        "codigo": "BE-1939-6.0",
        "nome": "Bloco Estrutural 19x19x39 cm (6.0 MPa)",
        "categoria": "blocos-estruturais",
        "categoria_label": "Blocos Estruturais",
        "destaque": False,
        "dimensoes": "19 x 19 x 39 cm",
        "resistencia": "6.0 MPa",
        "peso": "16.5 kg",
        "rendimento": "12.5 un / m²",
        "paletizacao": "84 peças / pallet",
        "norma": "ABNT NBR 6136 - Classe B",
        "unidade": "un",
        "qtd_minima": 50,
        "incremento": 50,
        "pronta_entrega": True,
        "descricao_curta": "Maior largura para isolamento acústico superior e obras pesadas.",
        "descricao_longa": "A família 19 confere maior inércia estrutural, excelente isolamento termoacústico e amplo espaço interno para tubulações.",
        "aplicacoes": ["Muros divisórios e perimetrais robustos", "Subsolos e garagens", "Fundações e poços de elevador"],
        "tipo_icone": "bloco-largo"
    },
    {
        "id": "meio-bloco-14",
        "codigo": "MB-1419",
        "nome": "Meio Bloco Estrutural 14x19x19 cm",
        "categoria": "blocos-estruturais",
        "categoria_label": "Blocos Estruturais",
        "destaque": False,
        "dimensoes": "14 x 19 x 19 cm",
        "resistencia": "4.5 MPa",
        "peso": "6.2 kg",
        "rendimento": "25.0 un / m²",
        "paletizacao": "240 peças / pallet",
        "norma": "ABNT NBR 6136",
        "unidade": "un",
        "qtd_minima": 50,
        "incremento": 25,
        "pronta_entrega": True,
        "descricao_curta": "Elimina quebras e desperdício nas amarrações de cantos e vãos.",
        "descricao_longa": "Indispensável para a modulação perfeita da alvenaria, evitando cortes manuais na obra.",
        "aplicacoes": ["Cantos de alvenaria estrutural", "Vãos de portas e janelas", "Amortecedores de modulação modular"],
        "tipo_icone": "meio-bloco"
    },
    {
        "id": "bloco-ved-09-39",
        "codigo": "BV-0939-2.5",
        "nome": "Bloco de Vedação 09x19x39 cm",
        "categoria": "blocos-vedacao",
        "categoria_label": "Blocos de Vedação",
        "destaque": True,
        "dimensoes": "09 x 19 x 39 cm",
        "resistencia": "2.5 MPa",
        "peso": "8.4 kg",
        "rendimento": "12.5 un / m²",
        "paletizacao": "160 peças / pallet",
        "norma": "ABNT NBR 6136 - Vedação",
        "unidade": "un",
        "qtd_minima": 100,
        "incremento": 50,
        "pronta_entrega": True,
        "descricao_curta": "Ideal para fechamento de vãos em estruturas de concreto armado.",
        "descricao_longa": "Bloco leve e ergonômico, perfeito para divisórias internas e fechamentos com menor consumo de reboco.",
        "aplicacoes": ["Paredes divisórias internas", "Fechamento de prédios com vigas e pilares", "Muros leves de divisa"],
        "tipo_icone": "bloco-fino"
    },
    {
        "id": "bloco-ved-14-39",
        "codigo": "BV-1439-3.0",
        "nome": "Bloco de Vedação 14x19x39 cm",
        "categoria": "blocos-vedacao",
        "categoria_label": "Blocos de Vedação",
        "destaque": False,
        "dimensoes": "14 x 19 x 39 cm",
        "resistencia": "3.0 MPa",
        "peso": "10.5 kg",
        "rendimento": "12.5 un / m²",
        "paletizacao": "120 peças / pallet",
        "norma": "ABNT NBR 6136",
        "unidade": "un",
        "qtd_minima": 100,
        "incremento": 50,
        "pronta_entrega": True,
        "descricao_curta": "Espessura padrão de 14cm para fachadas e fechamentos externos.",
        "descricao_longa": "Oferece excelente conforto térmico para fachadas e áreas externas com acabamento uniforme.",
        "aplicacoes": ["Fechamento perimetral", "Fachadas de galpões e prédios", "Muros de divisa residencial"],
        "tipo_icone": "bloco-padrao"
    },
    {
        "id": "canaleta-u-14",
        "codigo": "CAN-U-1439",
        "nome": "Canaleta de Concreto U 14x19x39 cm",
        "categoria": "canaletas",
        "categoria_label": "Canaletas & Compensadores",
        "destaque": True,
        "dimensoes": "14 x 19 x 39 cm",
        "resistencia": "4.5 MPa",
        "peso": "13.0 kg",
        "rendimento": "2.5 un / metro linear",
        "paletizacao": "120 peças / pallet",
        "norma": "ABNT NBR 6136",
        "unidade": "un",
        "qtd_minima": 20,
        "incremento": 10,
        "pronta_entrega": True,
        "descricao_curta": "Forma perdida para vergas, contra-vergas e cintas de amarração.",
        "descricao_longa": "Substitui caixarias de madeira na obra e agiliza a concretagem de vigas e vergas.",
        "aplicacoes": ["Cintas de amarração superior", "Vergas e contra-vergas", "Baldrames e vigas de travamento"],
        "tipo_icone": "canaleta-u"
    },
    {
        "id": "canaleta-j-14",
        "codigo": "CAN-J-1439",
        "nome": "Canaleta de Concreto J 14x19x39 cm",
        "categoria": "canaletas",
        "categoria_label": "Canaletas & Compensadores",
        "destaque": False,
        "dimensoes": "14 x 19 x 39 cm",
        "resistencia": "4.5 MPa",
        "peso": "13.8 kg",
        "rendimento": "2.5 un / metro linear",
        "paletizacao": "96 peças / pallet",
        "norma": "ABNT NBR 6136",
        "unidade": "un",
        "qtd_minima": 20,
        "incremento": 10,
        "pronta_entrega": False,
        "descricao_curta": "Apoio perimetral de lajes pré-moldadas e treliçadas.",
        "descricao_longa": "Aba rebaixada para perfeito encaixe e apoio das vigotas de lajes pré-moldadas.",
        "aplicacoes": ["Encaixe perimetral de lajes", "Apoio de vigotas treliçadas"],
        "tipo_icone": "canaleta-j"
    },
    {
        "id": "paver-holandes-06",
        "codigo": "PAV-HOL-06",
        "nome": "Piso Paver Retangular Holandês 10x20x06 cm",
        "categoria": "pisos-pavers",
        "categoria_label": "Pisos Intertravados",
        "destaque": True,
        "dimensoes": "10 x 20 x 06 cm",
        "resistencia": "35 MPa",
        "peso": "2.6 kg",
        "rendimento": "50 un / m²",
        "paletizacao": "12 m² / pallet",
        "norma": "ABNT NBR 9781",
        "unidade": "m²",
        "qtd_minima": 20,
        "incremento": 10,
        "pronta_entrega": True,
        "descricao_curta": "Piso intertravado de alta resistência para calçadas e garagens.",
        "descricao_longa": "Piso drenante e antiderrapante com liberação imediata ao tráfego leve e médio.",
        "aplicacoes": ["Calçadas públicas e condomínios", "Garagens residenciais", "Praças e áreas de lazer"],
        "tipo_icone": "paver-ret"
    },
    {
        "id": "paver-sextavado-08",
        "codigo": "PAV-SEX-08",
        "nome": "Piso Paver Sextavado 25x25x08 cm (35 MPa)",
        "categoria": "pisos-pavers",
        "categoria_label": "Pisos Intertravados",
        "destaque": False,
        "dimensoes": "25 x 25 x 08 cm",
        "resistencia": "35 MPa",
        "peso": "7.8 kg",
        "rendimento": "18 un / m²",
        "paletizacao": "10 m² / pallet",
        "norma": "ABNT NBR 9781 - Tráfego Pesado",
        "unidade": "m²",
        "qtd_minima": 30,
        "incremento": 10,
        "pronta_entrega": True,
        "descricao_curta": "Máxima capacidade de suporte para tráfego de caminhões e carretas.",
        "descricao_longa": "8 cm de espessura para resistir ao tráfego pesado e manobras em pátios logísticos.",
        "aplicacoes": ["Pátios de manobra logística", "Vias urbanas", "Galpões industriais"],
        "tipo_icone": "paver-sex"
    },
    {
        "id": "cimento-cp2-50",
        "codigo": "CIM-CP2-50",
        "nome": "Cimento Portland CP II-F 32 (Saco 50kg)",
        "categoria": "cimento-agregados",
        "categoria_label": "Cimento & Agregados",
        "destaque": True,
        "dimensoes": "Saco 50 kg",
        "resistencia": "32 MPa (28 dias)",
        "peso": "50.0 kg",
        "rendimento": "Conforme traço",
        "paletizacao": "40 sacos / pallet (2.000 kg)",
        "norma": "ABNT NBR 16697",
        "unidade": "saco",
        "qtd_minima": 10,
        "incremento": 5,
        "pronta_entrega": True,
        "descricao_curta": "Cimento multiuso de alta trabalhabilidade para todas as etapas da obra.",
        "descricao_longa": "Excelente plasticidade e resistência para fundações, estruturas e argamassas.",
        "aplicacoes": ["Concreto armado e fundações", "Argamassas de assentamento", "Calçadas e contrapisos"],
        "tipo_icone": "saco"
    },
    {
        "id": "areia-media-m3",
        "codigo": "AGR-AREIA-MED",
        "nome": "Areia Média Lavada (m³ ou Caminhão Fechado)",
        "categoria": "cimento-agregados",
        "categoria_label": "Cimento & Agregados",
        "destaque": False,
        "dimensoes": "Carga a granel (m³)",
        "resistencia": "Livre de impurezas",
        "peso": "~1.400 kg / m³",
        "rendimento": "Granulometria controlada",
        "paletizacao": "Entrega basculante",
        "norma": "ABNT NBR 7211",
        "unidade": "m³",
        "qtd_minima": 3,
        "incremento": 1,
        "pronta_entrega": True,
        "descricao_curta": "Areia selecionada para concreto usinado, contra-piso e alvenaria.",
        "descricao_longa": "Areia natural lavada, isenta de torrões de argila ou matéria orgânica.",
        "aplicacoes": ["Preparo de concretos", "Argamassas de assentamento", "Chapiscos e rebocos"],
        "tipo_icone": "agregado"
    },
    {
        "id": "argamassa-polimerica-massa",
        "codigo": "ARG-POL-03",
        "nome": "Argamassa Polimérica para Bloco (Bisnaga 3kg)",
        "categoria": "argamassas-ferragens",
        "categoria_label": "Argamassas & Aço",
        "destaque": True,
        "dimensoes": "Bisnaga 3.0 kg",
        "resistencia": "Até 4x superior à convencional",
        "peso": "3.0 kg",
        "rendimento": "Aprox. 1.5 a 2.0 kg / m²",
        "paletizacao": "Caixas com 6 bisnagas",
        "norma": "NBR 16590",
        "unidade": "bisnaga",
        "qtd_minima": 6,
        "incremento": 6,
        "pronta_entrega": True,
        "descricao_curta": "Massa pronta de assentamento: mais rápido, limpo e sem desperdício.",
        "descricao_longa": "Pronta para uso sem necessidade de água ou betoneira, aumentando a velocidade da obra.",
        "aplicacoes": ["Assentamento de blocos de concreto", "Alvenaria de vedação rápida"],
        "tipo_icone": "bisnaga"
    },
    {
        "id": "tela-soldada-q61",
        "codigo": "ACO-TELA-Q61",
        "nome": "Tela Soldada Nervurada Q-61 (Painel 2.45x6.00m)",
        "categoria": "argamassas-ferragens",
        "categoria_label": "Argamassas & Aço",
        "destaque": False,
        "dimensoes": "2.45 x 6.00 m (14.7 m²)",
        "resistencia": "Aço CA-60 (600 MPa)",
        "peso": "14.3 kg / painel",
        "rendimento": "Malha 15 x 15 cm - Fio 3.4 mm",
        "paletizacao": "Fardos de 50 painéis",
        "norma": "ABNT NBR 7481",
        "unidade": "painel",
        "qtd_minima": 2,
        "incremento": 1,
        "pronta_entrega": True,
        "descricao_curta": "Armadura soldada para lajes, pisos de concreto e contrapisos armados.",
        "descricao_longa": "Malha eletrosoldada com nós de fusão homogênea que evita fissuras e trincas térmicas.",
        "aplicacoes": ["Pisos e contrapisos de concreto", "Lajes pré-moldadas", "Paredes estruturais com tela"],
        "tipo_icone": "tela-aco"
    }
]
